language: rust
matrix:
  include:
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
    - rust: nightly
      env: TEST_FLAGS="--features nightly"
script:
  - cargo test $TEST_FLAGS
