language: rust
matrix:
  include:
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
        - FEATURES="--features simd"
    - rust: nightly
      env:
        - FEATURES="--features avx"
        - RUSTFLAGS="-C target-feature=+avx"
        - ARCH="x86_64"
addons:
  apt:
    packages:
      - gcc-multilib
script: |
  curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
  cargo test $FEATURES
