language: rust
matrix:
  include:
    - rust: 1.15.0
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
        - FEATURES="--features nightly"
    - rust: nightly
      env:
        - FEATURES="--features simd"
    - rust: nightly
      script:
        - RUSTFLAGS="-C target-feature=+avx" cargo build --features avx
script:
  - cargo test $FEATURES
