language: rust
matrix:
  include:
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
    - rust: nightly
      env: FEATURES="--features simd"
script:
  - cargo test $FEATURES
