language: rust
matrix:
  include:
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
        - FEATURES="--features simd"
    - rust: nightly
      env:
        - FEATURES="--features avx"
        - RUSTFLAGS="-C target-feature=+avx"
script:
  - cargo test $FEATURES
